version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node
        environment:
          PGUSER: root

      - image: mongo
        environment:
          MONGO_DB: contests

      - image: postgres
        environment:
          POSTGRES_DB: contests
          POSTGRES_USER: root
    steps:
      - checkout
      - run: yarn install
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client -y
      - run: dockerize -wait tcp://localhost:5432 -timeout 2m
      - run: psql -h 127.0.0.1 -U root -d contests -a -f database/test-pg-data.sql
      - run: dockerize -wait tcp://localhost:27017 -timeout 2m
      - run: node database/loadTestMongoData.js
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build